### ISSUE TITLE
Error:KeeperErrorCode = NodeExists for /onyx

### ISSUE THREAD

**Issue by gigafone** [onyx-platform/onyx-template#49] opened 2016-02-17 21:41 UTC
For example, on startup:

``` text
zookeeper_1 | 2016-02-17 18:37:07,438 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x152f0853bb30003 type:create cxid:0x2 zxid:0x33 txntype:-1 reqpath:n/a Error Path:/onyx Error:KeeperErrorCode = NodeExists for /onyx
```

I personally like to see less "noise" in logs, even if people "know" they are just warnings. (I see that it is marked as "INFO" but there is also "Exception" in there.)

I wonder if there is a better way/pattern to prevent this exception -- or at least to not show it -- since it isn't really "exceptional". (Is it?)

I also see that this exception is documented -- but I'm not sure this proves there isn't a better pattern:

> If a node with the same actual path already exists in the ZooKeeper, a KeeperException with error code KeeperException.NodeExists will be thrown. Note that since a different actual path is used for each invocation of creating sequential node with the same path argument, the call will never throw "file exists" KeeperException.

**Comment by MichaelDrogalis** [comment] 2016-02-17 22:05
@gigafone This log message comes straight out of ZooKeeper. I, too, think many of the message it emits at the `INFO` level would be better served at a different level. This isn't an exception, and most idiomatic usage of ZooKeeper is going to race to write the same znode by design. There's been [a patch](https://issues.apache.org/jira/browse/ZOOKEEPER-912) out for this for a long time. I wish there'd be some more activity on it, but alas, it remains stalled.

**Comment by gardnervickers** [comment] 2016-02-23 15:52
Going to close this as a non-issue

**Closed as completed by gardnervickers** 2016-02-23 15:52 UTC
Labels: wontfix

**Comment by JackZ0** [comment] 2018-12-11 06:40
Error:KeeperErrorCode = NodeExists for /consumers

**Comment by JackZ0** [comment] 2018-12-11 06:40
/brokers/ids Error:KeeperErrorCode = NodeExists for /brokers/ids

**Comment by JackZ0** [comment] 2018-12-11 06:41
what happened？  Got user-level KeeperException when processing sessionid:0x1679bfe14190000 type:create cxid:0x3 zxid:0x117 txntype:-1 reqpath:n/a Error Path:/brokers/topics Error:KeeperErrorCode = NodeExists for /brokers/topics

**Comment by mingtongzaohua** [comment] 2019-03-23 07:53
I have encountered the same error.
All I use is the default configuration, follow the official kafka quick start tutorial.
Examples of local production and consumption are normal.
However, when the external machine wants to send information to the server topic, it will not work.
